<?php
namespace yii\easyii\modules\entity\api;

use Yii;

use yii\data\ActiveDataProvider;
use yii\easyii\widgets\Fancybox;
use yii\easyii\modules\entity\models\Category;
use yii\easyii\modules\entity\models\Item;
use yii\web\NotFoundHttpException;
use yii\widgets\LinkPager;

/**
 * Catalog module API
 * @package yii\easyii\modules\entity\api
 *
 * @method static CategoryObject cat(mixed $id_slug) Get catalog category by id or slug
 * @method static array tree() Get catalog categories as tree
 * @method static array cats() Get catalog categories as flat array
 * @method static array items(array $options = []) Get list of items as ItemObject objects
 * @method static ItemObject get(mixed $id_slug) Get item object by id or slug
 * @method static mixed last(int $limit = 1, mixed $where = null) Get last items, use $where option for fetching items from special category
 * @method static void plugin() Applies FancyBox widget on photos called by box() function
 * @method static string pages() returns pagination html generated by yii\widgets\LinkPager widget.
 * @method static \stdClass pagination() returns yii\data\Pagination object.
 */

class Entity extends \yii\easyii\components\API
{
    private $_cats;
    private $_adp;
    private $_item = [];

    public function api_cat($id_slug)
    {
        if(!isset($this->_cats[$id_slug])) {
            $this->_cats[$id_slug] = new CategoryObject(Category::get($id_slug));
        }
        return $this->_cats[$id_slug];
    }

    public function api_tree()
    {
        return Category::tree();
    }

    public function api_cats($options = [])
    {
        $result = [];
        foreach(Category::cats() as $model){
            $result[] = new CategoryObject($model);
        }
        if(!empty($options['tags'])){
            foreach($result as $i => $item){
                if(!in_array($options['tags'], $item->tags)){
                    unset($result[$i]);
                }
            }
        }

        return $result;
    }

    public function api_items($options = [])
    {
        $result = [];

        $query = Item::find()->with('category')->status(Item::STATUS_ON);

        if(!empty($options['where'])){
            $query->andFilterWhere($options['where']);
        }
        $query->sort();

        $this->_adp = new ActiveDataProvider([
            'query' => $query,
            'pagination' => !empty($options['pagination']) ? $options['pagination'] : []
        ]);

        foreach($this->_adp->models as $model){
            $result[] = new ItemObject($model);
        }
        return $result;
    }

    public function api_last($limit = 1, $where = null)
    {
        $result = [];

        $query = Item::find()->sort()->status(Item::STATUS_ON)->limit($limit);
        if($where){
            $query->andFilterWhere($where);
        }

        foreach($query->all() as $item){
            $result[] = new ItemObject($item);
        }
        return $result;
    }

    public function api_get($id)
    {
        if(!isset($this->_item[$id])) {
            $this->_item[$id] = $this->findItem($id);
        }
        return $this->_item[$id];
    }

    public function api_pagination()
    {
        return $this->_adp ? $this->_adp->pagination : null;
    }

    public function api_pages()
    {
        return $this->_adp ? LinkPager::widget(['pagination' => $this->_adp->pagination]) : '';
    }

    public function api_plugin($options = [])
    {
        Fancybox::widget([
            'selector' => '.easyii-box',
            'options' => $options
        ]);
    }

    private function findItem($id)
    {
        if(!($item = Item::find()->where(['id' => ':id'], [':id' => $id])->status(Item::STATUS_ON)->one())){
            throw new NotFoundHttpException(Yii::t('easyii', 'Not found'));
        }

        return new ItemObject($item);
    }
}